const delay = (ms = 600) => new Promise((resolve) => setTimeout(resolve, ms));

// Mock API data for Petorium Vet Clinic Admin

export const mockData = {
  // Overview statistics
  stats: {
    totalPatients: 1247,
    patientsGrowth: "+2% this month",
    totalAppointments: 892,
    appointmentsGrowth: "+4.5% this week",
    todayAppointments: 34,
    appointmentsSchedule: "Today's schedule",
    monthlyRevenue: 12450,
    revenueGrowth: "+8% this month",
  },

  // Today's appointments
  todayAppointments: [
    {
      id: 1,
      petName: "Max",
      ownerName: "Sarah Johnson",
      time: "10:00 AM",
      type: "Khám tổng quát",
      status: "Đang khám",
    },
    {
      id: 2,
      petName: "Luna",
      ownerName: "Mike Smith",
      time: "11:30 AM",
      type: "Tiêm vaccine",
      status: "Đang chờ",
    },
    {
      id: 3,
      petName: "Charlie",
      ownerName: "Emma Davis",
      time: "02:04 PM",
      type: "Triệt sản",
      status: "Đã lên lịch",
    },
    {
      id: 4,
      petName: "Bella",
      ownerName: "John Wilson",
      time: "03:33 PM",
      type: "Spa",
      status: "Đã lên lịch",
    },
  ],

  // All appointments data
  appointments: [
    {
      id: 1,
      petName: "Max",
      ownerName: "Sarah Johnson",
      time: "11:00 AM",
      service: "Khám tổng quát",
      status: "Đã nhận",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 2,
      petName: "Luna",
      ownerName: "Michael Chen",
      time: "09:00 AM",
      service: "Tiêm Vacxin",
      status: "Đã nhận",
      date: "12-13-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 3,
      petName: "Charlie",
      ownerName: "Emily Rodriguez",
      time: "10:30 AM",
      service: "Khám sức",
      status: "Đã xác nhận",
      date: "12-25-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 4,
      petName: "Bella",
      ownerName: "David Thompson",
      time: "09:00 AM",
      service: "Khám tổng quát",
      status: "Đã nhận",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 5,
      petName: "Rocky",
      ownerName: "Jessica Williams",
      time: "11:30 AM",
      service: "Cạo rửa",
      status: "Urgent",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 6,
      petName: "Whiskers",
      ownerName: "Robert Brown",
      time: "03:00 PM",
      service: "Chăm sóc",
      status: "Đã nhận",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 7,
      petName: "Daisy",
      ownerName: "Amanda Davis",
      time: "02:00 PM",
      service: "Làm đẹp",
      status: "Approved",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 8,
      petName: "Oliver",
      ownerName: "Christopher Lee",
      time: "04:00 PM",
      service: "Follow-up",
      status: "Waiting",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 9,
      petName: "Milo",
      ownerName: "Sarah Johnson",
      time: "09:00 AM",
      service: "Grooming",
      status: "Approved",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 10,
      petName: "Coco",
      ownerName: "Rebecca Chen",
      time: "10:00 AM",
      service: "Check-up",
      status: "Pending",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 11,
      petName: "Buddy",
      ownerName: "Emily Rodriguez",
      time: "11:00 AM",
      service: "X-Ray",
      status: "Canceled",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 12,
      petName: "Simba",
      ownerName: "David Thompson",
      time: "01:00 PM",
      service: "Follow-up",
      status: "Waiting",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
    {
      id: 13,
      petName: "Nala",
      ownerName: "Sarah Johnson",
      time: "02:00 PM",
      service: "Follow-up",
      status: "Approved",
      date: "12-21-2025",
      doctor: "Dr. Sarah Johnson",
    },
    {
      id: 14,
      petName: "Luna",
      ownerName: "Michael Chen",
      time: "03:00 PM",
      service: "Check-up",
      status: "Pending",
      date: "12-21-2025",
      doctor: "Dr. Michael Johnson",
    },
  ],

  // Quick stats for right panel
  quickStats: {
    newPatientsToday: 23,
    avgExamTime: "15 min",
    petHotelGuests: 18,
    totalPets: 234,
  },

  // Doctors data
  doctors: [
    {
      id: 1,
      name: "Dr. Nguyễn Văn A",
      specialty: "Chuyên khoa nội",
      phone: "0901234567",
      email: "nguyenvana@petorium.com",
      avatar: null,
      schedule: ["T2", "T3", "T4", "T6"],
      monthlySchedule: {
        2: 1,
        3: 1,
        4: 2,
        5: 2,
        6: 5,
        7: 5,
        8: 5,
        9: 1,
        10: 1,
        11: 2,
        12: 2,
        13: 5,
        14: 5,
        15: 5,
        16: 1,
        17: 1,
      },
    },
    {
      id: 2,
      name: "Dr. Trần Thị B",
      specialty: "Chuyên khoa ngoại",
      phone: "0907654321",
      email: "tranthib@petorium.com",
      avatar: null,
      schedule: ["T2", "T4", "T5", "T7"],
      monthlySchedule: {
        2: 2,
        3: 3,
        4: 1,
        5: 1,
        6: 5,
        7: 5,
        8: 5,
        9: 2,
        10: 3,
        11: 1,
        12: 1,
        13: 5,
        14: 5,
        15: 5,
        16: 2,
        17: 3,
      },
    },
    {
      id: 3,
      name: "Dr. Lê Minh C",
      specialty: "Chuyên khoa da liễu",
      phone: "0918765432",
      email: "leminhc@petorium.com",
      avatar: null,
      schedule: ["T3", "T5", "T6", "T7"],
      monthlySchedule: {
        2: 3,
        3: 4,
        4: 4,
        5: 3,
        6: 5,
        7: 5,
        8: 5,
        9: 3,
        10: 4,
        11: 4,
        12: 3,
        13: 5,
        14: 5,
        15: 5,
        16: 3,
        17: 4,
      },
    },
  ],

  // Users/Customers data
  users: [
    {
      id: 1,
      name: "Sarah Johnson",
      email: "sarah.j@email.com",
      phone: "0912345678",
      pets: ["Max"],
      joinDate: "2024-01-15",
    },
    {
      id: 2,
      name: "Mike Smith",
      email: "mike.smith@email.com",
      phone: "0923456789",
      pets: ["Luna", "Rocky"],
      joinDate: "2024-02-20",
    },
    {
      id: 3,
      name: "Emma Davis",
      email: "emma.davis@email.com",
      phone: "0934567890",
      pets: ["Charlie"],
      joinDate: "2024-03-10",
    },
    {
      id: 4,
      name: "John Wilson",
      email: "john.w@email.com",
      phone: "0945678901",
      pets: ["Bella", "Max"],
      joinDate: "2024-04-05",
    },
    {
      id: 5,
      name: "Nguyễn Văn An",
      email: "nguyenvanan@email.com",
      phone: "0956789012",
      pets: ["Miu"],
      joinDate: "2024-05-12",
    },
    {
      id: 6,
      name: "Trần Thị Bình",
      email: "tranthib@email.com",
      phone: "0967890123",
      pets: ["Bobby", "Coco"],
      joinDate: "2024-06-18",
    },
  ],

  // Pets data
  pets: [
    {
      id: 1,
      name: "Max",
      species: "Dog",
      breed: "Golden Retriever",
      age: "5 years",
      gender: "Male",
      owner: "John Smith",
      ownerContact: "(555) 123-4567",
      ownerId: 1,
      status: "Healthy",
      lastVisit: "Dec 15, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 2,
      name: "Luna",
      species: "Cat",
      breed: "Persian",
      age: "3 years",
      gender: "Female",
      owner: "Emily Davis",
      ownerContact: "(555) 234-5678",
      ownerId: 2,
      status: "Healthy",
      lastVisit: "Dec 18, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 3,
      name: "Charlie",
      species: "Dog",
      breed: "Beagle",
      age: "7 years",
      gender: "Male",
      owner: "Robert Wilson",
      ownerContact: "(555) 345-6789",
      ownerId: 3,
      status: "Warning",
      lastVisit: "Dec 20, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 4,
      name: "Bella",
      species: "Dog",
      breed: "Labrador",
      age: "2 years",
      gender: "Female",
      owner: "David Anderson",
      ownerContact: "(555) 456-7890",
      ownerId: 4,
      status: "Healthy",
      lastVisit: "Dec 16, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 5,
      name: "Rocky",
      species: "Dog",
      breed: "German Shepherd",
      age: "4 years",
      gender: "Male",
      owner: "Michael Johnson",
      ownerContact: "(555) 567-8901",
      ownerId: 5,
      status: "Healthy",
      lastVisit: "Dec 14, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 6,
      name: "Minnnie",
      species: "Cat",
      breed: "Tabby",
      age: "1 year",
      gender: "Female",
      owner: "Jennifer Lee",
      ownerContact: "(555) 678-9012",
      ownerId: 6,
      status: "Unhealthy",
      lastVisit: "Dec 19, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 7,
      name: "Buddy",
      species: "Dog",
      breed: "Poodle",
      age: "3 years",
      gender: "Male",
      owner: "David Anderson",
      ownerContact: "(555) 789-0123",
      ownerId: 7,
      status: "Healthy",
      lastVisit: "Dec 15, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 8,
      name: "Whiskers",
      species: "Cat",
      breed: "Maine Coon",
      age: "4 years",
      gender: "Male",
      owner: "Lisa Taylor",
      ownerContact: "(555) 890-1234",
      ownerId: 8,
      status: "Healthy",
      lastVisit: "Dec 11, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 9,
      name: "Daisy",
      species: "Dog",
      breed: "Chihuahua",
      age: "6 years",
      gender: "Female",
      owner: "James Thomas",
      ownerContact: "(555) 901-2345",
      ownerId: 9,
      status: "Healthy",
      lastVisit: "Dec 17, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 10,
      name: "Oliver",
      species: "Cat",
      breed: "Bengal",
      age: "2 years",
      gender: "Male",
      owner: "Mary Garcia",
      ownerContact: "(555) 012-3456",
      ownerId: 10,
      status: "Healthy",
      lastVisit: "Dec 13, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 11,
      name: "Rex",
      species: "Dog",
      breed: "Bulldog",
      age: "5 years",
      gender: "Male",
      owner: "William Lee",
      ownerContact: "(555) 123-4567",
      ownerId: 11,
      status: "Unhealthy",
      lastVisit: "Dec 18, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 12,
      name: "Simba",
      species: "Cat",
      breed: "Siamese",
      age: "3 years",
      gender: "Male",
      owner: "Patricia Martinez",
      ownerContact: "(555) 234-5678",
      ownerId: 12,
      status: "Healthy",
      lastVisit: "Dec 16, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 13,
      name: "Molly",
      species: "Dog",
      breed: "Cocker Spaniel",
      age: "8 years",
      gender: "Female",
      owner: "Richard Clark",
      ownerContact: "(555) 345-6789",
      ownerId: 13,
      status: "Warning",
      lastVisit: "Dec 9, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 14,
      name: "Shadow",
      species: "Cat",
      breed: "Scottish Fold",
      age: "3 years",
      gender: "Male",
      owner: "Barbara Hall",
      ownerContact: "(555) 456-7890",
      ownerId: 14,
      status: "Healthy",
      lastVisit: "Dec 14, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
    {
      id: 15,
      name: "Toby",
      species: "Dog",
      breed: "Boxer",
      age: "4 years",
      gender: "Male",
      owner: "Thomas Lewis",
      ownerContact: "(555) 567-8901",
      ownerId: 15,
      status: "Healthy",
      lastVisit: "Dec 10, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 16,
      name: "Coco",
      species: "Dog",
      breed: "Pomeranian",
      age: "10 years",
      gender: "Female",
      owner: "Susan Rodriguez",
      ownerContact: "(555) 678-9012",
      ownerId: 16,
      status: "Healthy",
      lastVisit: "Dec 12, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 17,
      name: "Spike",
      species: "Dog",
      breed: "Doberman",
      age: "6 years",
      gender: "Male",
      owner: "Charles White",
      ownerContact: "(555) 789-0123",
      ownerId: 17,
      status: "Healthy",
      lastVisit: "Dec 15, 2024",
      assignedDoctor: "Dr. Sarah Johnson",
    },
    {
      id: 18,
      name: "Fluffy",
      species: "Cat",
      breed: "Ragdoll",
      age: "4 years",
      gender: "Female",
      owner: "Karen Harris",
      ownerContact: "(555) 890-1234",
      ownerId: 18,
      status: "Healthy",
      lastVisit: "Dec 16, 2024",
      assignedDoctor: "Dr. Michael Johnson",
    },
  ],

  // Services data
  services: [
    {
      id: 1,
      name: "General Check-up",
      category: "Examination",
      duration: "30 min",
      price: 150,
      description: "Comprehensive health examination for pets",
    },
    {
      id: 2,
      name: "Vaccination",
      category: "Preventive",
      duration: "15 min",
      price: 85,
      description: "Essential vaccinations for disease prevention",
    },
    {
      id: 3,
      name: "Dental Cleaning",
      category: "Dental",
      duration: "45 min",
      price: 250,
      description: "Professional dental cleaning and oral care",
    },
    {
      id: 4,
      name: "Surgery Consultation",
      category: "Surgery",
      duration: "45 min",
      price: 200,
      description: "Pre-surgery consultation and assessment",
    },
    {
      id: 5,
      name: "X-Ray Imaging",
      category: "Diagnostic",
      duration: "30 min",
      price: 180,
      description: "Digital X-ray imaging services",
    },
    {
      id: 6,
      name: "Blood Test",
      category: "Diagnostic",
      duration: "20 min",
      price: 120,
      description: "Comprehensive blood work analysis",
    },
    {
      id: 7,
      name: "Grooming",
      category: "Wellness",
      duration: "60 min",
      price: 95,
      description: "Professional pet grooming services",
    },
    {
      id: 8,
      name: "Emergency Care",
      category: "Emergency",
      duration: "Variable",
      price: 350,
      description: "24/7 emergency veterinary care",
    },
  ],

  // Medications & Vaccines data
  medications: [
    {
      id: 1,
      name: "Amoxicillin",
      type: "Medication",
      quantity: 145,
      unit: "tablets",
      pricePerUnit: 2.5,
      expiryDate: "Jun 15, 2025",
      description: "Antibiotic for bacterial infections",
    },
    {
      id: 2,
      name: "Carprofen",
      type: "Medication",
      quantity: 89,
      unit: "tablets",
      pricePerUnit: 3.2,
      expiryDate: "Apr 30, 2025",
      description: "Anti-inflammatory pain relief",
    },
    {
      id: 3,
      name: "Rabies Vaccine",
      type: "Vaccine",
      quantity: 76,
      unit: "doses",
      pricePerUnit: 12,
      nextOrder: "Apr 15, 2025",
      description: "Rabies prevention vaccine",
    },
    {
      id: 4,
      name: "DHPP Vaccine",
      type: "Vaccine",
      quantity: 92,
      unit: "doses",
      pricePerUnit: 15,
      nextOrder: "May 1, 2024",
      description: "Distemper, Hepatitis, Parainfluenza, Parvovirus vaccine",
    },
    {
      id: 5,
      name: "Prednisone",
      type: "Medication",
      quantity: 67,
      unit: "tablets",
      pricePerUnit: 1.8,
      expiryDate: "Aug 20, 2025",
      description: "Corticosteroid for inflammation",
    },
    {
      id: 6,
      name: "Flea & Tick Prevention",
      type: "Medication",
      quantity: 134,
      unit: "doses",
      pricePerUnit: 8.5,
      expiryDate: "Dec 31, 2025",
      description: "Monthly flea and tick prevention",
    },
    {
      id: 7,
      name: "Feline Leukemia Vaccine",
      type: "Vaccine",
      quantity: 45,
      unit: "doses",
      pricePerUnit: 18,
      nextOrder: "Jun 1, 2025",
      description: "Feline leukemia virus prevention",
    },
    {
      id: 8,
      name: "Heartworm Prevention",
      type: "Medication",
      quantity: 98,
      unit: "tablets",
      pricePerUnit: 6.5,
      expiryDate: "Sep 15, 2025",
      description: "Monthly heartworm prevention",
    },
  ],

  // Visits data (Lượt khám)
  visits: [
    {
      id: 1,
      slotId: "#001",
      checkIn: "09:00",
      checkOut: "09:45",
      petName: "Max",
      ownerName: "Sarah Johnson",
      service: "Check-up",
      doctor: "Dr. Smith",
      status: "Hoàn thành",
      date: "12-21-2025",
    },
    {
      id: 2,
      slotId: "#002",
      checkIn: "09:30",
      checkOut: "-",
      petName: "Luna",
      ownerName: "Michael Chen",
      service: "Vaccination",
      doctor: "Dr. Johnson",
      status: "Đang khám",
      date: "12-21-2025",
    },
    {
      id: 3,
      slotId: "#003",
      checkIn: "10:00",
      checkOut: "-",
      petName: "Bella",
      ownerName: "Emma Wilson",
      service: "Dental",
      doctor: "Dr. Williams",
      status: "Chờ",
      date: "12-21-2025",
    },
    {
      id: 4,
      slotId: "#004",
      checkIn: "10:30",
      checkOut: "11:15",
      petName: "Charlie",
      ownerName: "James Rodriguez",
      service: "Surgery",
      doctor: "Dr. Smith",
      status: "Hoàn thành",
      date: "12-21-2025",
    },
    {
      id: 5,
      slotId: "#005",
      checkIn: "11:00",
      checkOut: "-",
      petName: "Lucy",
      ownerName: "Olivia Martinez",
      service: "Check-up",
      doctor: "Dr. Johnson",
      status: "Chờ",
      date: "12-21-2025",
    },
    {
      id: 6,
      slotId: "#006",
      checkIn: "11:30",
      checkOut: "12:00",
      petName: "Cooper",
      ownerName: "William Brown",
      service: "Follow-up",
      doctor: "Dr. Williams",
      status: "Hoàn thành",
      date: "12-21-2025",
    },
    {
      id: 7,
      slotId: "#007",
      checkIn: "13:00",
      checkOut: "13:45",
      petName: "Daisy",
      ownerName: "Sophia Anderson",
      service: "Vaccination",
      doctor: "Dr. Smith",
      status: "Hoàn trả",
      date: "12-21-2025",
    },
    {
      id: 8,
      slotId: "#008",
      checkIn: "13:30",
      checkOut: "-",
      petName: "Rocky",
      ownerName: "Daniel Thompson",
      service: "Check-up",
      doctor: "Dr. Johnson",
      status: "Đang khám",
      date: "12-21-2025",
    },
    {
      id: 9,
      slotId: "#009",
      checkIn: "14:00",
      checkOut: "-",
      petName: "Milo",
      ownerName: "Isabella Garcia",
      service: "Dental",
      doctor: "Dr. Williams",
      status: "Chờ",
      date: "12-21-2025",
    },
    {
      id: 10,
      slotId: "#010",
      checkIn: "14:30",
      checkOut: "15:10",
      petName: "Zoe",
      ownerName: "Ethan Davis",
      service: "Follow-up",
      doctor: "Dr. Smith",
      status: "Hoàn trả",
      date: "12-21-2025",
    },
    {
      id: 11,
      slotId: "#011",
      checkIn: "15:00",
      checkOut: "-",
      petName: "Oliver",
      ownerName: "Ava Miller",
      service: "Check-up",
      doctor: "Dr. Johnson",
      status: "Chờ",
      date: "12-21-2025",
    },
    {
      id: 12,
      slotId: "#012",
      checkIn: "15:30",
      checkOut: "16:05",
      petName: "Sophie",
      ownerName: "Noah Wilson",
      service: "Vaccination",
      doctor: "Dr. Williams",
      status: "Hoàn trả",
      date: "12-21-2025",
    },
    {
      id: 13,
      slotId: "#013",
      checkIn: "10:00",
      checkOut: "10:45",
      petName: "Max",
      ownerName: "Sarah Johnson",
      service: "Dental",
      doctor: "Dr. Smith",
      status: "Hoàn thành",
      date: "12-13-2025",
    },
    {
      id: 14,
      slotId: "#014",
      checkIn: "11:00",
      checkOut: "11:30",
      petName: "Bella",
      ownerName: "Emma Wilson",
      service: "Follow-up",
      doctor: "Dr. Williams",
      status: "Hoàn thành",
      date: "12-13-2025",
    },
    {
      id: 15,
      slotId: "#015",
      checkIn: "14:00",
      checkOut: "14:40",
      petName: "Charlie",
      ownerName: "James Rodriguez",
      service: "Check-up",
      doctor: "Dr. Johnson",
      status: "Hoàn thành",
      date: "12-25-2025",
    },
  ],

  // Medical Records data
  medicalRecords: [
    {
      id: 1,
      reportId: "RPT-2024-001",
      petId: "PET-0231",
      petName: "Max",
      petSpecies: "Dog",
      petBreed: "Golden Retriever",
      petAge: "4 years",
      ownerName: "Sarah Johnson",
      ownerId: "OWN-1042",
      doctorName: "Dr. Emily Carter",
      serviceType: "Khám tổng quát",
      serviceName: "Routine Health Check",
      reportDate: "2024-03-15",
      reportTime: "09:00 AM",
      status: "Đã xong",
      symptoms: "Mất nội năng",
      diagnosis: "Chán ăn",
      treatmentDetails: ["Tinh trạng sức khỏe ổn định", "Nhạy cảm về tiêu hóa"],
      medicalHistory: ["Điều trị răng sáng", "Theo dõi cân nặng"],
      prescription: "Thực phẩm bổ sung men vi sinh",
      dosage: "7",
      frequency: "1 lần/ ngày",
      medicalCondition: "Không có bệnh mãn tính",
      images: [
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400",
        "https://images.unsplash.com/photo-1551076805-e1869033e561?w=400",
        "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
      ],
    },
    {
      id: 2,
      reportId: "RPT-2024-002",
      petId: "PET-0145",
      petName: "Luna",
      petSpecies: "Cat",
      petBreed: "Persian",
      petAge: "2 years",
      ownerName: "Michael Chen",
      ownerId: "OWN-2154",
      doctorName: "Dr. James Wilson",
      serviceType: "Tiêm vacxin",
      serviceName: "Vaccination",
      reportDate: "2024-03-14",
      reportTime: "02:30 PM",
      status: "Đã xong",
      symptoms: "None",
      diagnosis: "Healthy - Routine vaccination",
      treatmentDetails: ["Tiêm vacxin FVRCP", "Kiểm tra sức khỏe tổng quát"],
      medicalHistory: [
        "Tiêm vacxin lần trước: 2023-03-14",
        "Không có phản ứng phụ",
      ],
      prescription: "Không cần thuốc",
      dosage: "N/A",
      frequency: "N/A",
      medicalCondition: "Khỏe mạnh",
      images: [],
    },
    {
      id: 3,
      reportId: "RPT-2024-003",
      petId: "PET-0387",
      petName: "Bella",
      petSpecies: "Dog",
      petBreed: "Labrador",
      petAge: "5 years",
      ownerName: "Emma Davis",
      ownerId: "OWN-3298",
      doctorName: "Dr. Emily Carter",
      serviceType: "Khám răng",
      serviceName: "Dental Care",
      reportDate: "2024-03-13",
      reportTime: "11:00 AM",
      status: "Đang chờ",
      symptoms: "Bad breath, difficulty eating",
      diagnosis: "Dental plaque and tartar buildup",
      treatmentDetails: ["Vệ sinh răng miệng", "Lấy cao răng"],
      medicalHistory: ["Lần đầu làm sạch răng", "Không có tiền sử nha khoa"],
      prescription: "Nước súc miệng cho thú cưng",
      dosage: "Daily",
      frequency: "2 lần/ngày",
      medicalCondition: "Healthy overall",
      images: [],
    },
    {
      id: 4,
      reportId: "RPT-2024-004",
      petId: "PET-0492",
      petName: "Charlie",
      petSpecies: "Dog",
      petBreed: "Beagle",
      petAge: "3 years",
      ownerName: "Robert Taylor",
      ownerId: "OWN-4567",
      doctorName: "Dr. Sarah Martinez",
      serviceType: "Cấp cứu",
      serviceName: "Emergency Care",
      reportDate: "2024-03-12",
      reportTime: "04:45 PM",
      status: "Đã xong",
      symptoms: "Vomiting, lethargy",
      diagnosis: "Acute gastroenteritis",
      treatmentDetails: [
        "IV fluids",
        "Anti-nausea medication",
        "Observation for 24 hours",
      ],
      medicalHistory: ["First emergency visit", "No previous GI issues"],
      prescription: "Probiotic supplements",
      dosage: "5",
      frequency: "2 lần/ngày",
      medicalCondition: "Recovered",
      images: [],
    },
    {
      id: 5,
      reportId: "RPT-2024-005",
      petId: "PET-0598",
      petName: "Milo",
      petSpecies: "Cat",
      petBreed: "Siamese",
      petAge: "6 years",
      ownerName: "Jennifer White",
      ownerId: "OWN-5678",
      doctorName: "Dr. James Wilson",
      serviceType: "Da liễu",
      serviceName: "Dermatology",
      reportDate: "2024-03-11",
      reportTime: "10:15 AM",
      status: "Đang khám",
      symptoms: "Scratching, hair loss",
      diagnosis: "Allergic dermatitis",
      treatmentDetails: [
        "Allergy testing",
        "Topical medication",
        "Dietary adjustment",
      ],
      medicalHistory: ["Seasonal allergies", "Previous skin issues"],
      prescription: "Anti-histamine cream",
      dosage: "Apply twice daily",
      frequency: "2 lần/ngày",
      medicalCondition: "Chronic skin sensitivity",
      images: [],
    },
    {
      id: 6,
      reportId: "RPT-2024-006",
      petId: "PET-0621",
      petName: "Rocky",
      petSpecies: "Dog",
      petBreed: "German Shepherd",
      petAge: "7 years",
      ownerName: "Daniel Thompson",
      ownerId: "OWN-6789",
      doctorName: "Dr. Emily Carter",
      serviceType: "Khám tổng quát",
      serviceName: "Follow-up Check",
      reportDate: "2024-03-10",
      reportTime: "01:00 PM",
      status: "Đã xong",
      symptoms: "None",
      diagnosis: "Routine follow-up",
      treatmentDetails: ["Weight management check", "Joint health assessment"],
      medicalHistory: ["Arthritis treatment ongoing", "Weight controlled"],
      prescription: "Joint supplement",
      dosage: "10",
      frequency: "1 lần/ngày",
      medicalCondition: "Mild arthritis",
      images: [],
    },
    {
      id: 7,
      reportId: "RPT-2024-007",
      petId: "PET-0754",
      petName: "Daisy",
      petSpecies: "Dog",
      petBreed: "Poodle",
      petAge: "3 years",
      ownerName: "Sophia Anderson",
      ownerId: "OWN-7890",
      doctorName: "Dr. Sarah Martinez",
      serviceType: "Khám tổng quát",
      serviceName: "Health Check",
      reportDate: "2024-03-09",
      reportTime: "03:15 PM",
      status: "Đã xong",
      symptoms: "None",
      diagnosis: "Healthy",
      treatmentDetails: ["General health check", "Vaccination status reviewed"],
      medicalHistory: ["All vaccinations up to date", "No health issues"],
      prescription: "None",
      dosage: "N/A",
      frequency: "N/A",
      medicalCondition: "Excellent health",
      images: [],
    },
    {
      id: 8,
      reportId: "RPT-2024-008",
      petId: "PET-0887",
      petName: "Oliver",
      petSpecies: "Cat",
      petBreed: "Maine Coon",
      petAge: "4 years",
      ownerName: "Ava Miller",
      ownerId: "OWN-8901",
      doctorName: "Dr. James Wilson",
      serviceType: "Khám tổng quát",
      serviceName: "Routine Check",
      reportDate: "2024-03-08",
      reportTime: "11:30 AM",
      status: "Đã xong",
      symptoms: "None",
      diagnosis: "Healthy",
      treatmentDetails: ["Weight check", "Dental examination"],
      medicalHistory: ["Regular check-ups", "No issues"],
      prescription: "None",
      dosage: "N/A",
      frequency: "N/A",
      medicalCondition: "Healthy",
      images: [],
    },
  ],

  // Invoices data
  invoices: [
    {
      id: 1,
      invoiceId: "INV-001",
      patientName: "Max",
      ownerName: "Sarah Johnson",
      service: "Annual Check-up",
      amount: 450,
      date: "2024-03-15",
      dueDate: "2024-03-15",
      status: "Paid",
      subtotal: 450,
      tax: 0,
      services: [
        { name: "General Examination", price: 150 },
        { name: "Blood Test", price: 120 },
        { name: "Vaccination", price: 85 },
      ],
      medications: [
        { name: "Vitamin Supplement", price: 45 },
        { name: "Flea Prevention", price: 50 },
      ],
    },
    {
      id: 2,
      invoiceId: "INV-002",
      patientName: "Luna",
      ownerName: "Mike Smith",
      service: "Vaccination",
      amount: 85,
      date: "2024-03-20",
      dueDate: "2024-03-25",
      status: "Pending",
      subtotal: 600,
      tax: 0,
      services: [{ name: "Tiêm vaccin", price: 200 }],
      medications: [
        { name: "Thuốc tiêm 1 :)))", price: 200 },
        { name: "Thuốc tiêm 2 :)))", price: 200 },
      ],
    },
    {
      id: 3,
      invoiceId: "INV-003",
      patientName: "Charlie",
      ownerName: "Emma Davis",
      service: "Surgery",
      amount: 1200,
      date: "2024-03-10",
      dueDate: "2024-03-10",
      status: "Paid",
      subtotal: 1200,
      tax: 0,
      services: [
        { name: "Surgical Procedure", price: 800 },
        { name: "Anesthesia", price: 250 },
      ],
      medications: [
        { name: "Pain Relief", price: 75 },
        { name: "Antibiotics", price: 75 },
      ],
    },
    {
      id: 4,
      invoiceId: "INV-004",
      patientName: "Bella",
      ownerName: "John Wilson",
      service: "Dental Cleaning",
      amount: 250,
      date: "2024-03-05",
      dueDate: "2024-03-05",
      status: "Overdue",
      subtotal: 250,
      tax: 0,
      services: [{ name: "Dental Cleaning", price: 200 }],
      medications: [{ name: "Dental Care Solution", price: 50 }],
    },
    {
      id: 5,
      invoiceId: "INV-005",
      patientName: "Rocky",
      ownerName: "Lisa Brown",
      service: "Follow-up Visit",
      amount: 75,
      date: "2024-03-22",
      dueDate: "2024-03-22",
      status: "Paid",
      subtotal: 75,
      tax: 0,
      services: [{ name: "Follow-up Consultation", price: 75 }],
      medications: [],
    },
    {
      id: 6,
      invoiceId: "INV-006",
      patientName: "Daisy",
      ownerName: "Tom Anderson",
      service: "X-Ray Imaging",
      amount: 320,
      date: "2024-03-18",
      dueDate: "2024-03-18",
      status: "Pending",
      subtotal: 320,
      tax: 0,
      services: [
        { name: "X-Ray Service", price: 180 },
        { name: "Consultation", price: 90 },
      ],
      medications: [{ name: "Pain Relief", price: 50 }],
    },
  ],

  // Hotel bookings data
  hotelBookings: [
    {
      id: 1,
      petName: "Daisy",
      ownerName: "James Morrison",
      checkIn: "Dec 14, 2025",
      checkOut: "Dec 25, 2025",
      roomNumber: "D-001",
      status: "Ongoing",
      bookingType: "current",
    },
    {
      id: 2,
      petName: "Andy",
      ownerName: "Daniel Harris",
      checkIn: "Dec 16, 2025",
      checkOut: "Dec 30, 2025",
      roomNumber: "D-002",
      status: "Ongoing",
      bookingType: "current",
    },
    {
      id: 3,
      petName: "Lucky",
      ownerName: "Harry Moore",
      checkIn: "Dec 18, 2025",
      checkOut: "Jan 06, 2026",
      roomNumber: "D-021",
      status: "Ongoing",
      bookingType: "current",
    },
    {
      id: 4,
      petName: "Shiba",
      ownerName: "Ashley Davis",
      checkIn: "Dec 12, 2025",
      checkOut: "Dec 24, 2025",
      roomNumber: "D-041",
      status: "Ongoing",
      bookingType: "current",
    },
    {
      id: 5,
      petName: "Charlie",
      ownerName: "Baby Williams",
      checkIn: "Dec 12, 2025",
      checkOut: "Dec 23, 2025",
      roomNumber: "D-044",
      status: "Ongoing",
      bookingType: "current",
    },
    {
      id: 6,
      petName: "Mia",
      ownerName: "Gentle Johnson",
      checkIn: "Dec 24, 2025",
      checkOut: "Jan 02, 2026",
      roomNumber: "D-011",
      status: "Upcoming",
      bookingType: "upcoming",
    },
    {
      id: 7,
      petName: "Charlie",
      ownerName: "Emily Williams",
      checkIn: "Dec 24, 2025",
      checkOut: "Jan 05, 2026",
      roomNumber: "D-022",
      status: "Upcoming",
      bookingType: "upcoming",
    },
    {
      id: 8,
      petName: "Cooper",
      ownerName: "Lisa Anderson",
      checkIn: "Dec 26, 2025",
      checkOut: "Jan 10, 2026",
      roomNumber: "D-023",
      status: "Upcoming",
      bookingType: "upcoming",
    },
    {
      id: 9,
      petName: "Duke",
      ownerName: "James Martinez",
      checkIn: "Dec 28, 2025",
      checkOut: "Jan 05, 2026",
      roomNumber: "D-031",
      status: "Upcoming",
      bookingType: "upcoming",
    },
    {
      id: 10,
      petName: "Luna",
      ownerName: "Robert Wilson",
      checkIn: "Dec 30, 2025",
      checkOut: "Jan 14, 2026",
      roomNumber: "D-032",
      status: "Upcoming",
      bookingType: "upcoming",
    },
  ],

  // Hotel rooms
  hotelRooms: [
    { number: "D-001", status: "Occupied", floor: 1 },
    { number: "D-002", status: "Occupied", floor: 1 },
    { number: "D-003", status: "Available", floor: 1 },
    { number: "D-004", status: "Available", floor: 1 },
    { number: "D-005", status: "Available", floor: 1 },
    { number: "D-011", status: "Reserved", floor: 2 },
    { number: "D-012", status: "Available", floor: 2 },
    { number: "D-013", status: "Available", floor: 2 },
    { number: "D-014", status: "Available", floor: 2 },
    { number: "D-015", status: "Available", floor: 2 },
    { number: "D-021", status: "Occupied", floor: 3 },
    { number: "D-022", status: "Reserved", floor: 3 },
    { number: "D-023", status: "Reserved", floor: 3 },
    { number: "D-024", status: "Available", floor: 3 },
    { number: "D-025", status: "Available", floor: 3 },
    { number: "D-031", status: "Reserved", floor: 4 },
    { number: "D-032", status: "Reserved", floor: 4 },
    { number: "D-033", status: "Available", floor: 4 },
    { number: "D-034", status: "Available", floor: 4 },
    { number: "D-035", status: "Available", floor: 4 },
    { number: "D-041", status: "Occupied", floor: 5 },
    { number: "D-042", status: "Available", floor: 5 },
    { number: "D-043", status: "Available", floor: 5 },
    { number: "D-044", status: "Occupied", floor: 5 },
    { number: "D-045", status: "Available", floor: 5 },
  ],
};

// Mock API functions
export const api = {
  // Get overview stats
  getStats: () => {
    return Promise.resolve(mockData.stats);
  },

  // Get today's appointments
  getTodayAppointments: () => {
    return Promise.resolve(mockData.todayAppointments);
  },

  // Get all appointments
  getAppointments: () => {
    return Promise.resolve(mockData.appointments);
  },

  // Get quick stats
  getQuickStats: () => {
    return Promise.resolve(mockData.quickStats);
  },

  // Get all doctors
  getDoctors: () => {
    return Promise.resolve(mockData.doctors);
  },

  // Add a new doctor
  addDoctor: (doctor) => {
    const newDoctor = {
      ...doctor,
      id: mockData.doctors.length + 1,
    };
    mockData.doctors.push(newDoctor);
    return Promise.resolve(newDoctor);
  },

  // Get all users
  getUsers: () => {
    return Promise.resolve(mockData.users);
  },

  // Get all pets
  getPets: () => {
    return Promise.resolve(mockData.pets);
  },

  // Get pet by ID
  getPetById: (id) => {
    const pet = mockData.pets.find((p) => p.id === parseInt(id));
    return Promise.resolve(pet);
  },

  // Get all services
  getServices: () => {
    return Promise.resolve(mockData.services);
  },

  // Get all medications
  getMedications: () => {
    return Promise.resolve(mockData.medications);
  },

  // Get all visits
  getVisits: () => {
    return Promise.resolve(mockData.visits);
  },

  // Get all medical records
  getMedicalRecords: () => {
    return Promise.resolve(mockData.medicalRecords);
  },

  // Get medical record by report ID
  getMedicalRecordByReportId: (reportId) => {
    const record = mockData.medicalRecords.find((r) => r.reportId === reportId);
    return Promise.resolve(record);
  },

  // Get all invoices
  getInvoices: () => {
    return Promise.resolve(mockData.invoices);
  },

  // Get invoice by ID
  getInvoiceById: (id) => {
    const invoice = mockData.invoices.find((i) => i.id === parseInt(id));
    return Promise.resolve(invoice);
  },

  // Get hotel bookings
  getHotelBookings: () => {
    return Promise.resolve(mockData.hotelBookings);
  },

  // Get hotel rooms
  getHotelRooms: () => {
    return Promise.resolve(mockData.hotelRooms);
  },
};

/* ===== FEEDBACKS ===== */
export const getReviews = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: 1,
          name: "Trang Lê",
          pet: "Max (Chó Poodle)",
          content:
            "Bác sĩ ở đây siêu dễ thương luôn! Bé chó nhà mình đi khám mà cứ vẫy đuôi suốt.",
          rating: 5,
        },
        {
          id: 2,
          name: "Hải Đăng",
          pet: "Luna (Mèo Anh lông dài)",
          content:
            "Phòng khám rất chuyên nghiệp, bác sĩ nhẹ nhàng và giải thích rõ ràng.",
          rating: 5,
        },
        {
          id: 3,
          name: "Tú Anh",
          pet: "Đen (Chó cỏ)",
          content:
            "Thật sự biết ơn vì đã cứu bé cún của mình. Rất đáng tin cậy!",
          rating: 5,
        },
      ]);
    }, 600);
  });

export const submitFeedback = (data) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        message: "Feedback submitted",
        data,
      });
    }, 800);
  });
