"""initial

Revision ID: 168b5e07707d
Revises: 
Create Date: 2025-12-29 11:00:05.833566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '168b5e07707d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_tokens',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Enum('1', '2', '3', '4', '5', name='feedback_rating_enum'), nullable=False),
    sa.Column('status', sa.Enum('Hidden', 'Show', name='feedback_status_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('feedback_id')
    )

    # Ensure the appointment_status_enum type exists before altering the appointment.status column
    # Use the existing naming convention 'enum_appointment_status' to match any pre-existing enum in the DB
    appointment_status_enum = postgresql.ENUM(
        'Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='enum_appointment_status'
    )
    appointment_status_enum.create(op.get_bind(), checkfirst=True)

    # Convert existing status values into the enum during type change using the legacy enum labels
    # We map old textual statuses into the existing enum label set (pending, confirmed, completed, cancelled)
    op.execute("""
        ALTER TABLE appointment
        ALTER COLUMN status
        TYPE enum_appointment_status
        USING (CASE
            WHEN status = 'pending' THEN 'pending'
            WHEN status IN ('confirmed','completed') THEN 'confirmed'
            WHEN status = 'cancelled' THEN 'cancelled'
            ELSE 'pending'
        END)::enum_appointment_status;
    """)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        # Add booking_date with a server default to populate existing rows safely
        batch_op.add_column(sa.Column('booking_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        # status column already converted above; mark it as non-nullable via alter_column
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='enum_appointment_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::enum_appointment_status"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('appointment_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('appointment_doctor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('appointment_pet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('service')
        batch_op.drop_column('pet_breed')
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('pet_name')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('timeslot')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('date')
        batch_op.drop_column('pet_id')

    # Remove the temporary server default so the column is strict (no default)
    op.alter_column('appointment', 'booking_date', server_default=None, existing_type=sa.Date())

    op.drop_table('services')
    op.drop_table('doctor')
    op.drop_table('pets')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'customer'::character varying"))
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('phone')
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'customer'::character varying"))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timeslot', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pet_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pet_breed', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_pet_id_fkey', 'pets', ['pet_id'], ['pet_id'])
        batch_op.create_foreign_key('appointment_doctor_id_fkey', 'doctor', ['doctor_id'], ['doctor_id'])
        batch_op.create_foreign_key('appointment_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='enum_appointment_status'),
               type_=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', name='enum_appointment_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::enum_appointment_status"))
        batch_op.drop_column('created_at')
        batch_op.drop_column('booking_date')

    op.create_table('pets',
    sa.Column('pet_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('breed', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'unknown', name='enum_pets_gender'), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='pets_user_id_fkey'),
    sa.PrimaryKeyConstraint('pet_id', name='pets_pkey')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doctor_id', name='doctor_pkey')
    )
    op.create_table('services',
    sa.Column('service_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('service_id', name='services_pkey')
    )
    op.drop_table('feedback')
    op.drop_table('blocked_tokens')

    # Drop the appointment_status_enum type created in upgrade
    appointment_status_enum = postgresql.ENUM(name='enum_appointment_status')
    appointment_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
