"""add missing tables from models (autogenerate)

Revision ID: fedd0f5df241
Revises: 6c9d7b8a9add
Create Date: 2025-12-30 06:17:01.767379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fedd0f5df241'
down_revision = '6c9d7b8a9add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('diagnose_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medicine',
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=9, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('pethouse',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=9, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=9, scale=0), nullable=False),
    sa.Column('service_category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('symptom',
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('symptom_id')
    )
    op.create_table('doctor_slot',
    sa.Column('doctor_slot_id', sa.Integer(), nullable=False),
    sa.Column('shift', postgresql.ENUM('NONE', '9-12', '12-18', '9-13', '13-18', '9-17', '10-18', name='doctor_shift_enum'), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_slot_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_hotel',
    sa.Column('petboard_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('petboard_id')
    )
    op.create_table('invoice_hotel',
    sa.Column('in_hotel_id', sa.Integer(), nullable=False),
    sa.Column('petboard_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=9, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['pethouse.hotel_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['petboard_id'], ['pet_hotel.petboard_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('in_hotel_id'),
    sa.UniqueConstraint('petboard_id')
    )
    op.create_table('slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('Đang chờ', 'Đang khám', 'Đã xong', name='slot_status_enum'), nullable=False),
    sa.Column('doctor_slot_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_slot_id'], ['doctor_slot.doctor_slot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('patient_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('Đang chờ khám', 'Đang khám', 'Đã khám xong', name='patient_report_status_enum'), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.slot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=9, scale=0), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('medical_image',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('captured_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('report_diagnose',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('diagnose_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnose_id'], ['disease.diagnose_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'diagnose_id')
    )
    op.create_table('report_medicine',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.medicine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'medicine_id')
    )
    op.create_table('report_service',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'service_id')
    )
    op.create_table('report_symptom',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.symptom_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'symptom_id')
    )

    # Ensure the new enum type exists before altering the appointment.status column
    appointment_status_enum = postgresql.ENUM(
        'Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='appointment_status_enum'
    )
    appointment_status_enum.create(op.get_bind(), checkfirst=True)

    # Convert existing appointment.status values to the new type using an explicit USING cast
    op.execute("""
        ALTER TABLE appointment
        ALTER COLUMN status
        TYPE appointment_status_enum
        USING (status::text::appointment_status_enum);
    """)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        # Create doctor FK (column already exists)
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['doctor_id'], ondelete='SET NULL')

    # Ensure orphan pets have a valid owner: create a placeholder user and assign any NULL user_id pets to it
    op.execute("""
        INSERT INTO users (first_name, last_name, email, password, user_type, is_active)
        VALUES ('Orphan', 'Owner', 'orphan@vetclinic.local', 'pbkdf2:sha256:260000$seed$orphan', 'customer', true)
        ON CONFLICT (email) DO NOTHING;
    """)
    op.execute("""
        UPDATE pets
        SET user_id = (SELECT user_id FROM users WHERE email = 'orphan@vetclinic.local')
        WHERE user_id IS NULL;
    """)

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('pets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('color')
        batch_op.drop_column('weight')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pets_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('breed',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='appointment_status_enum'),
               type_=postgresql.ENUM('Đang chờ xác nhận', 'Đặt lịch hẹn thành công', 'Đã hủy lịch hẹn', name='enum_appointment_status'),
               existing_nullable=False)

    op.drop_table('report_symptom')
    op.drop_table('report_service')
    op.drop_table('report_medicine')
    op.drop_table('report_diagnose')
    op.drop_table('medical_image')
    op.drop_table('invoice')
    op.drop_table('patient_report')
    op.drop_table('slot')
    op.drop_table('invoice_hotel')
    op.drop_table('pet_hotel')
    op.drop_table('refresh_tokens')
    op.drop_table('doctor_slot')
    op.drop_table('symptom')
    op.drop_table('service')
    op.drop_table('pethouse')
    op.drop_table('medicine')
    op.drop_table('doctor')
    op.drop_table('disease')
    # ### end Alembic commands ###
